# Generated by Django 2.0.7 on 2018-08-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, verbose_name='邮箱')),
                ('wechat', models.CharField(max_length=255, verbose_name='微信')),
                ('phone', models.CharField(max_length=255, verbose_name='手机号')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否逻辑删除')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.CharField(max_length=255, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=100, verbose_name='手机号')),
                ('Message', models.TextField(verbose_name='留言')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否逻辑删除')),
            ],
        ),
    ]
