# Generated by Django 2.0.7 on 2018-08-14 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': '个人信息', 'verbose_name_plural': '个人信息'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '留言信息', 'verbose_name_plural': '留言信息'},
        ),
        migrations.AddField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='留言时间'),
        ),
    ]
