# Generated by Django 2.0.7 on 2018-08-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20180814_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Message',
            new_name='message',
        ),
    ]
