# Generated by Django 2.0.7 on 2018-08-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20180814_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.CharField(max_length=255, verbose_name='邮箱★'),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='手机号★'),
        ),
        migrations.AlterField(
            model_name='info',
            name='wechat',
            field=models.CharField(max_length=255, verbose_name='微信★'),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='邮箱★'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(verbose_name='留言★'),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=100, verbose_name='姓名★'),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='手机号★'),
        ),
    ]
