# Generated by Django 2.0.7 on 2018-08-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='images/blog/img-4.jpg', upload_to='images/blog', verbose_name='图片'),
        ),
    ]
