# Generated by Django 2.0.7 on 2018-08-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180816_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='是否逻辑删除'),
        ),
    ]
