# Generated by Django 2.0.7 on 2018-08-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_isdelete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '博客评论', 'verbose_name_plural': '博客评论'},
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='images/blog/img-4.jpg', upload_to='images/blog/poster', verbose_name='图片'),
        ),
    ]
