# Generated by Django 2.0.7 on 2018-09-05 14:06

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180822_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', max_length=1024000000000, verbose_name='文章正文★'),
        ),
    ]
