# Generated by Django 2.0.7 on 2018-09-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180905_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time'], 'verbose_name': '博客评论', 'verbose_name_plural': '博客评论'},
        ),
    ]
