# Generated by Django 2.0.7 on 2018-09-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180909_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='upload/blog/poster/img-4.jpg', upload_to='upload/blog/poster', verbose_name='图片'),
        ),
    ]
