# Generated by Django 2.0.7 on 2018-09-11 01:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180909_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='评论回复正文★')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否逻辑删除')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Comment', verbose_name='评论★')),
            ],
            options={
                'verbose_name': '博客评论回复',
                'verbose_name_plural': '博客评论回复',
                'ordering': ['created_time'],
            },
        ),
    ]
