# Generated by Django 2.0.7 on 2018-08-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='主页滚动句')),
                ('img', models.ImageField(upload_to='homeBg', verbose_name='主页背景图')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否逻辑删除')),
            ],
        ),
    ]
