# Generated by Django 2.0.7 on 2018-08-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewsNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todayNum', models.IntegerField(verbose_name='当日点击量')),
                ('date', models.DateField(verbose_name='时间')),
                ('sumNum', models.IntegerField(verbose_name='总点击量')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否逻辑删除')),
            ],
        ),
        migrations.AlterModelOptions(
            name='wheel',
            options={'verbose_name': '主页滚动图', 'verbose_name_plural': '主页滚动图'},
        ),
        migrations.AlterField(
            model_name='wheel',
            name='img',
            field=models.ImageField(upload_to='images/wheel', verbose_name='主页背景图'),
        ),
    ]
