# Generated by Django 2.0.7 on 2018-08-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180813_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewsnum',
            options={'ordering': ['-sumNum'], 'verbose_name': '浏览量', 'verbose_name_plural': '浏览量'},
        ),
    ]
