# Generated by Django 2.0.7 on 2018-08-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180813_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheel',
            name='img',
            field=models.ImageField(upload_to='upload/wheel', verbose_name='主页背景图★'),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='text',
            field=models.CharField(max_length=255, verbose_name='主页滚动句★'),
        ),
    ]
