# Generated by Django 2.0.7 on 2018-08-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/about', verbose_name='图片')),
                ('text', models.TextField(verbose_name='关于详细')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否逻辑删除')),
            ],
            options={
                'verbose_name': '关于页详细',
                'verbose_name_plural': '关于页详细',
            },
        ),
    ]
