# Generated by Django 2.0.7 on 2018-09-06 06:11

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20180822_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='text',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', max_length=1024000000000, verbose_name='关于详细★'),
        ),
    ]
