# Generated by Django 2.0.7 on 2018-08-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20180822_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='info',
            field=models.CharField(max_length=255, verbose_name='概述★'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=100, verbose_name='项目名字★'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='url',
            field=models.CharField(max_length=255, verbose_name='项目网址★'),
        ),
    ]
