# Generated by Django 2.0.7 on 2018-09-05 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20180822_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['name'], 'verbose_name': '个人作品', 'verbose_name_plural': '个人作品'},
        ),
    ]
