# Generated by Django 2.0.7 on 2018-09-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20180905_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='downloadNum',
            field=models.IntegerField(default=0, verbose_name='下载量'),
        ),
    ]
